package jcbhmr:resast;

interface resast {
  record class {
    id: option<ident>,
    super-class: option<box-expr>,
    body: class-boody,
  }

  resource box-expr {
    deref: func() -> expr;
  }
}

world host {
  export resast;
}
